import{S,i as u,a as w}from"./assets/vendor-951421c8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const q=new S(".photo-container a",{captionsData:"alt",captionDelay:250}),k=document.querySelector(".search-form"),m=document.querySelector(".photo-list"),i=document.querySelector('[data-action="load-more"]'),p=document.querySelector(".loader"),h=document.querySelector(".loader-load-more"),s="is-hidden";let c="",d=1,y=0;const E=40;k.addEventListener("submit",P);async function P(a){a.preventDefault(),m.innerHTML="",p.classList.remove(s),d=1;const t=a.currentTarget;if(c=t.elements.query.value.trim(),!c){p.classList.add(s),i.classList.add(s),u.show({message:"Please enter your request",position:"topRight",color:"yellow"});return}try{const{hits:r,totalHits:n}=await f(c);y=Math.ceil(n/E),L(r,m),r.length>0&&r.length!==n?(i.classList.remove(s),i.addEventListener("click",g)):r.length?i.classList.add(s):(i.classList.add(s),u.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"center",color:"red"}))}catch(r){console.log(r)}finally{p.classList.add(s),t.reset()}}async function f(a,t=1){const r="https://pixabay.com/api",n="41870399-9b44301246ceb98c07efd626a";try{return(await w.get(`${r}/`,{params:{key:n,q:a,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:t}})).data}catch{u.error({title:"Error",position:"center",color:"red",message:"Sorry! Try later! Server not working"}),console.error(error.message)}}async function g(){d+=1,h.classList.remove(s),i.classList.add(s);const a=document.querySelector(".gallery-item").getBoundingClientRect();try{const{hits:t}=await f(c,d);L(t,m)}catch(t){console.log(t)}finally{window.scrollBy({top:a.height*2,left:0,behavior:"smooth"}),h.classList.add(s),i.classList.remove(s),d===y&&(i.classList.add(s),i.removeEventListener("click",g),u.show({color:"blue",position:"bottomCenter",message:"We're sorry, but you've reached the end of search results."}))}}function L(a){const t=a.map(({webformatURL:r,largeImageURL:n,tags:e,likes:o,views:l,comments:b,downloads:v})=>`<li class="gallery-item">
  <a class="gallery-link" href="${n}">
    <img
      class="gallery-image"
      src="${r}"
      alt="${e}"
    />
  </a><div class="gallery-descr">
   <p>Likes: <br><span>${o}</span></p>
   <p>Views: <br><span>${l}</span></p>
   <p>Comment: <br><span>${b}</span></p>
   <p>Downloads: <br><span>${v}</span></p></div>
</li>`).join("");m.insertAdjacentHTML("beforeend",t),q.refresh()}
//# sourceMappingURL=commonHelpers.js.map
