import{S,i as u,a as w}from"./assets/vendor-951421c8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const q=new S(".photo-container a",{captionsData:"alt",captionDelay:250}),k=document.querySelector(".search-form"),m=document.querySelector(".photo-list"),a=document.querySelector('[data-action="load-more"]'),p=document.querySelector(".loader"),h=document.querySelector(".loader-load-more"),r="is-hidden";let c="",d=1,y=0;const E=15;k.addEventListener("submit",P);async function P(n){n.preventDefault(),m.innerHTML="",p.classList.remove(r),d=1,a.classList.add(r);const t=n.currentTarget;if(c=t.elements.query.value.trim(),!c){p.classList.add(r),a.classList.add(r),u.show({message:"Please enter your request",position:"topRight",color:"yellow"});return}try{const{hits:s,totalHits:i}=await f(c);y=Math.ceil(i/E),L(s,m),s.length>0&&s.length!==i?(a.classList.remove(r),a.addEventListener("click",g)):s.length?a.classList.add(r):(a.classList.add(r),u.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"center",color:"red"}))}catch(s){console.log(s)}finally{p.classList.add(r),t.reset()}}async function f(n,t=1){const s="https://pixabay.com/api",i="41870399-9b44301246ceb98c07efd626a";try{return(await w.get(`${s}/`,{params:{key:i,q:n,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:t}})).data}catch{u.error({title:"Error",position:"center",color:"red",message:"Sorry! Try later! Server not working"}),console.error(error.message)}}async function g(){d+=1,h.classList.remove(r),a.classList.add(r);const n=document.querySelector(".gallery-item").getBoundingClientRect();try{const{hits:t}=await f(c,d);L(t,m)}catch(t){console.log(t)}finally{window.scrollBy({top:n.height*2,left:0,behavior:"smooth"}),h.classList.add(r),a.classList.remove(r),d===y&&(a.classList.add(r),a.removeEventListener("click",g),u.show({color:"blue",position:"bottomCenter",message:"We're sorry, but you've reached the end of search results."}))}}function L(n){const t=n.map(({webformatURL:s,largeImageURL:i,tags:e,likes:o,views:l,comments:b,downloads:v})=>`<li class="gallery-item">
  <a class="gallery-link" href="${i}">
    <img
      class="gallery-image"
      src="${s}"
      alt="${e}"
    />
  </a><div class="gallery-descr">
   <p>Likes: <br><span>${o}</span></p>
   <p>Views: <br><span>${l}</span></p>
   <p>Comment: <br><span>${b}</span></p>
   <p>Downloads: <br><span>${v}</span></p></div>
</li>`).join("");m.insertAdjacentHTML("beforeend",t),q.refresh()}
//# sourceMappingURL=commonHelpers.js.map
