import{S as w,i as u,a as q}from"./assets/vendor-951421c8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const k=new w(".photo-container a",{captionsData:"alt",captionDelay:250}),E=document.querySelector(".search-form"),m=document.querySelector(".photo-list"),n=document.querySelector('[data-action="load-more"]'),p=document.querySelector(".loader"),h=document.querySelector(".loader-load-more"),r="is-hidden";let c="",d=1,y=0;const f=40,P="https://pixabay.com/api",$="41870399-9b44301246ceb98c07efd626a";E.addEventListener("submit",M);async function M(a){a.preventDefault(),m.innerHTML="",p.classList.remove(r),d=1;const t=a.currentTarget;if(c=t.elements.query.value.trim(),!c){p.classList.add(r),n.classList.add(r),u.show({message:"Please enter your request",position:"topRight",color:"yellow"});return}try{const{hits:s,totalHits:i}=await g(c);y=Math.ceil(i/f),b(s,m),s.length>0&&s.length!==i?(n.classList.remove(r),n.addEventListener("click",L)):s.length?n.classList.add(r):(n.classList.add(r),u.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"center",color:"red"}))}catch(s){console.log(s)}finally{p.classList.add(r),t.reset()}}async function g(a,t=1){try{return(await q.get(`${P}/`,{params:{key:$,q:a,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:f,page:t}})).data}catch{u.error({title:"Error",position:"center",color:"red",message:"Sorry! Try later! Server not working"}),console.error(error.message)}}async function L(){d+=1,h.classList.remove(r),n.classList.add(r);const a=document.querySelector(".gallery-item").getBoundingClientRect();try{const{hits:t}=await g(c,d);b(t,m)}catch(t){console.log(t)}finally{window.scrollBy({top:a.height*2,left:0,behavior:"smooth"}),h.classList.add(r),n.classList.remove(r),d===y&&(n.classList.add(r),n.removeEventListener("click",L),u.show({color:"blue",position:"bottomCenter",message:"We're sorry, but you've reached the end of search results."}))}}function b(a){const t=a.map(({webformatURL:s,largeImageURL:i,tags:e,likes:o,views:l,comments:v,downloads:S})=>`<li class="gallery-item">
  <a class="gallery-link" href="${i}">
    <img
      class="gallery-image"
      src="${s}"
      alt="${e}"
    />
  </a><div class="gallery-descr">
   <p>Likes: <br><span>${o}</span></p>
   <p>Views: <br><span>${l}</span></p>
   <p>Comment: <br><span>${v}</span></p>
   <p>Downloads: <br><span>${S}</span></p></div>
</li>`).join("");m.insertAdjacentHTML("beforeend",t),k.refresh()}
//# sourceMappingURL=commonHelpers.js.map
